### PR TITLE
Merge into admin-form

### PR DESCRIPTION
**Pull request by whitef0x0**
Need to do this before we can merge into tellform master branch

### CODE REVIEW

**Comment by whitef0x0** [comment]
@lalop have you looked into this?

**Comment by lalop** [comment]
hello @whitef0x0 , you mean merge the master into admin-form ?

**Comment by whitef0x0** [comment]
yep

**Comment by lalop** [comment]
I have rebased all master into this branch

**Comment by whitef0x0** [comment]
@lalop does it work?

**Comment by lalop** [comment]
I always have the bug of the redirection
capture d ecran 2016-06-05 a 01 30 15

**Comment by whitef0x0** [comment]
Set your BASE_URL in the .env file to your address. In this case it would be http://localhost:3000

**Comment by whitef0x0** [comment]
I can't seem to get it to work. I think it would be easier if you just took your translating parts and improvements and added them to individual files in master, without changing the directory structure.

**Comment by lalop** [comment]
I don't think this is necessary since it's the default url in development `baseUrl: process.env.BASE_URL || 'http://localhost:3000',`
Anyway I did it and I allways have the same issue.
What doesn't work for you ?

**Comment by lalop** [comment]
Did you made a bower install then a build ?

**Comment by whitef0x0** [comment]
yep

**Comment by whitef0x0** [comment]
I got it to work but the form fields won't display

**Comment by whitef0x0** [comment]
*Won't render in the edit view

**Comment by lalop** [comment]
Do you have any idea of how to stop the redirection issue ?

**Pull request merged**
